package com.amar.expense_tracker.entity;
// Generated 11 Aug 2026, 9:58:31 pm by Hibernate Tools 7.3.13.Final


import jakarta.persistence.*;

import java.io.Serializable;
import java.util.UUID;

import org.hibernate.annotations.UuidGenerator;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Accounts generated by hbm2java
 */
@Entity
@Table(name="accounts"
    ,schema="public"
)
public class Accounts  implements Serializable {


     private UUID id;
     private Users users;
     private String name;
     private String institution;
     private String accountType;
     private String lastFourDigits;
     private String currency;
     private boolean active;
     private Date createdAt;
     private Date updatedAt;
     private Set<Transactions> transactionses = new HashSet<Transactions>(0);
     private Set<Statements> statementses = new HashSet<Statements>(0);

    public Accounts() {
    }

	
    public Accounts(UUID id, Users users, String name, String accountType, String currency, boolean active, Date createdAt, Date updatedAt) {
        this.id = id;
        this.users = users;
        this.name = name;
        this.accountType = accountType;
        this.currency = currency;
        this.active = active;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }
    public Accounts(UUID id, Users users, String name, String institution, String accountType, String lastFourDigits, String currency, boolean active, Date createdAt, Date updatedAt, Set<Transactions> transactionses, Set<Statements> statementses) {
       this.id = id;
       this.users = users;
       this.name = name;
       this.institution = institution;
       this.accountType = accountType;
       this.lastFourDigits = lastFourDigits;
       this.currency = currency;
       this.active = active;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.transactionses = transactionses;
       this.statementses = statementses;
    }
   
     @Id 
     @GeneratedValue 
     @UuidGenerator 

    
    @Column(name="id", unique=true, nullable=false)
    public UUID getId() {
        return this.id;
    }
    
    public void setId(UUID id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    
    @Column(name="name", nullable=false, length=150)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="institution", length=150)
    public String getInstitution() {
        return this.institution;
    }
    
    public void setInstitution(String institution) {
        this.institution = institution;
    }

    
    @Column(name="account_type", nullable=false)
    public String getAccountType() {
        return this.accountType;
    }
    
    public void setAccountType(String accountType) {
        this.accountType = accountType;
    }

    
    @Column(name="last_four_digits", length=4)
    public String getLastFourDigits() {
        return this.lastFourDigits;
    }
    
    public void setLastFourDigits(String lastFourDigits) {
        this.lastFourDigits = lastFourDigits;
    }

    
    @Column(name="currency", nullable=false, length=3)
    public String getCurrency() {
        return this.currency;
    }
    
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    
    @Column(name="active", nullable=false)
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false, length=35)
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at", nullable=false, length=35)
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="accounts")
    public Set<Transactions> getTransactionses() {
        return this.transactionses;
    }
    
    public void setTransactionses(Set<Transactions> transactionses) {
        this.transactionses = transactionses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="accounts")
    public Set<Statements> getStatementses() {
        return this.statementses;
    }
    
    public void setStatementses(Set<Statements> statementses) {
        this.statementses = statementses;
    }




}


