package com.amar.expense_tracker.entity;
// Generated 11 Aug 2026, 9:58:31 pm by Hibernate Tools 7.3.13.Final


import jakarta.persistence.*;

import java.io.Serializable;
import java.util.UUID;

import org.hibernate.annotations.UuidGenerator;
import java.math.BigDecimal;
import java.util.Date;

/**
 * AiCategorization generated by hbm2java
 */
@Entity
@Table(name="ai_categorization"
    ,schema="public"
)
public class AiCategorization  implements Serializable {


     private UUID id;
     private Transactions transactions;
     private Categories categories;
     private String modelName;
     private BigDecimal confidence;
     private String reasoning;
     private String status;
     private Date createdAt;

    public AiCategorization() {
    }

	
    public AiCategorization(UUID id, Transactions transactions, String status, Date createdAt) {
        this.id = id;
        this.transactions = transactions;
        this.status = status;
        this.createdAt = createdAt;
    }
    public AiCategorization(UUID id, Transactions transactions, Categories categories, String modelName, BigDecimal confidence, String reasoning, String status, Date createdAt) {
       this.id = id;
       this.transactions = transactions;
       this.categories = categories;
       this.modelName = modelName;
       this.confidence = confidence;
       this.reasoning = reasoning;
       this.status = status;
       this.createdAt = createdAt;
    }
   
     @Id 
     @GeneratedValue 
     @UuidGenerator 

    
    @Column(name="id", unique=true, nullable=false)
    public UUID getId() {
        return this.id;
    }
    
    public void setId(UUID id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="transaction_id", nullable=false)
    public Transactions getTransactions() {
        return this.transactions;
    }
    
    public void setTransactions(Transactions transactions) {
        this.transactions = transactions;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="predicted_category_id")
    public Categories getCategories() {
        return this.categories;
    }
    
    public void setCategories(Categories categories) {
        this.categories = categories;
    }

    
    @Column(name="model_name", length=100)
    public String getModelName() {
        return this.modelName;
    }
    
    public void setModelName(String modelName) {
        this.modelName = modelName;
    }

    
    @Column(name="confidence", precision=5, scale=4)
    public BigDecimal getConfidence() {
        return this.confidence;
    }
    
    public void setConfidence(BigDecimal confidence) {
        this.confidence = confidence;
    }

    
    @Column(name="reasoning")
    public String getReasoning() {
        return this.reasoning;
    }
    
    public void setReasoning(String reasoning) {
        this.reasoning = reasoning;
    }

    
    @Column(name="status", nullable=false)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false, length=35)
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }




}


