package com.amar.expense_tracker.entity;
// Generated 11 Aug 2026, 9:58:31 pm by Hibernate Tools 7.3.13.Final


import jakarta.persistence.*;

import java.io.Serializable;
import java.util.UUID;

import org.hibernate.annotations.UuidGenerator;
import java.math.BigDecimal;
import java.util.Date;

/**
 * CategoryMonthlySummary generated by hbm2java
 */
@Entity
@Table(name="category_monthly_summary"
    ,schema="public"
    , uniqueConstraints = @UniqueConstraint(columnNames={"user_id", "year", "month", "category_id"}) 
)
public class CategoryMonthlySummary  implements Serializable {


     private UUID id;
     private Users users;
     private Categories categories;
     private int year;
     private int month;
     private BigDecimal totalAmount;
     private BigDecimal percentageOfExpense;
     private BigDecimal percentageOfCredit;
     private Date createdAt;
     private Date updatedAt;

    public CategoryMonthlySummary() {
    }

    public CategoryMonthlySummary(UUID id, Users users, Categories categories, int year, int month, BigDecimal totalAmount, BigDecimal percentageOfExpense, BigDecimal percentageOfCredit, Date createdAt, Date updatedAt) {
       this.id = id;
       this.users = users;
       this.categories = categories;
       this.year = year;
       this.month = month;
       this.totalAmount = totalAmount;
       this.percentageOfExpense = percentageOfExpense;
       this.percentageOfCredit = percentageOfCredit;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
    }
   
     @Id 
     @GeneratedValue 
     @UuidGenerator 

    
    @Column(name="id", unique=true, nullable=false)
    public UUID getId() {
        return this.id;
    }
    
    public void setId(UUID id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="category_id", nullable=false)
    public Categories getCategories() {
        return this.categories;
    }
    
    public void setCategories(Categories categories) {
        this.categories = categories;
    }

    
    @Column(name="year", nullable=false)
    public int getYear() {
        return this.year;
    }
    
    public void setYear(int year) {
        this.year = year;
    }

    
    @Column(name="month", nullable=false)
    public int getMonth() {
        return this.month;
    }
    
    public void setMonth(int month) {
        this.month = month;
    }

    
    @Column(name="total_amount", nullable=false, precision=19, scale=4)
    public BigDecimal getTotalAmount() {
        return this.totalAmount;
    }
    
    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    
    @Column(name="percentage_of_expense", nullable=false, precision=7, scale=4)
    public BigDecimal getPercentageOfExpense() {
        return this.percentageOfExpense;
    }
    
    public void setPercentageOfExpense(BigDecimal percentageOfExpense) {
        this.percentageOfExpense = percentageOfExpense;
    }

    
    @Column(name="percentage_of_credit", nullable=false, precision=7, scale=4)
    public BigDecimal getPercentageOfCredit() {
        return this.percentageOfCredit;
    }
    
    public void setPercentageOfCredit(BigDecimal percentageOfCredit) {
        this.percentageOfCredit = percentageOfCredit;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false, length=35)
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at", nullable=false, length=35)
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }




}


