package com.amar.expense_tracker.entity;
// Generated 11 Aug 2026, 9:58:31 pm by Hibernate Tools 7.3.13.Final


import jakarta.persistence.*;

import java.io.Serializable;
import java.util.UUID;

import org.hibernate.annotations.UuidGenerator;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Categories generated by hbm2java
 */
@Entity
@Table(name="categories"
    ,schema="public"
    , uniqueConstraints = @UniqueConstraint(columnNames={"name", "parent_id"}) 
)
public class Categories  implements Serializable {


     private UUID id;
     private Categories categories;
     private String name;
     private String categoryType;
     private boolean active;
     private Date createdAt;
     private Date updatedAt;
     private Set<AiCategorization> aiCategorizations = new HashSet<AiCategorization>(0);
     private Set<CategoryMonthlySummary> categoryMonthlySummaries = new HashSet<CategoryMonthlySummary>(0);
     private Set<UserCategoryRules> userCategoryRuleses = new HashSet<UserCategoryRules>(0);
     private Set<Transactions> transactionses = new HashSet<Transactions>(0);
     private Set<Categories> categorieses = new HashSet<Categories>(0);

    public Categories() {
    }

	
    public Categories(UUID id, String name, String categoryType, boolean active, Date createdAt, Date updatedAt) {
        this.id = id;
        this.name = name;
        this.categoryType = categoryType;
        this.active = active;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }
    public Categories(UUID id, Categories categories, String name, String categoryType, boolean active, Date createdAt, Date updatedAt, Set<AiCategorization> aiCategorizations, Set<CategoryMonthlySummary> categoryMonthlySummaries, Set<UserCategoryRules> userCategoryRuleses, Set<Transactions> transactionses, Set<Categories> categorieses) {
       this.id = id;
       this.categories = categories;
       this.name = name;
       this.categoryType = categoryType;
       this.active = active;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.aiCategorizations = aiCategorizations;
       this.categoryMonthlySummaries = categoryMonthlySummaries;
       this.userCategoryRuleses = userCategoryRuleses;
       this.transactionses = transactionses;
       this.categorieses = categorieses;
    }
   
     @Id 
     @GeneratedValue 
     @UuidGenerator 

    
    @Column(name="id", unique=true, nullable=false)
    public UUID getId() {
        return this.id;
    }
    
    public void setId(UUID id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="parent_id")
    public Categories getCategories() {
        return this.categories;
    }
    
    public void setCategories(Categories categories) {
        this.categories = categories;
    }

    
    @Column(name="name", nullable=false, length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="category_type", nullable=false)
    public String getCategoryType() {
        return this.categoryType;
    }
    
    public void setCategoryType(String categoryType) {
        this.categoryType = categoryType;
    }

    
    @Column(name="active", nullable=false)
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false, length=35)
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at", nullable=false, length=35)
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="categories")
    public Set<AiCategorization> getAiCategorizations() {
        return this.aiCategorizations;
    }
    
    public void setAiCategorizations(Set<AiCategorization> aiCategorizations) {
        this.aiCategorizations = aiCategorizations;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="categories")
    public Set<CategoryMonthlySummary> getCategoryMonthlySummaries() {
        return this.categoryMonthlySummaries;
    }
    
    public void setCategoryMonthlySummaries(Set<CategoryMonthlySummary> categoryMonthlySummaries) {
        this.categoryMonthlySummaries = categoryMonthlySummaries;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="categories")
    public Set<UserCategoryRules> getUserCategoryRuleses() {
        return this.userCategoryRuleses;
    }
    
    public void setUserCategoryRuleses(Set<UserCategoryRules> userCategoryRuleses) {
        this.userCategoryRuleses = userCategoryRuleses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="categories")
    public Set<Transactions> getTransactionses() {
        return this.transactionses;
    }
    
    public void setTransactionses(Set<Transactions> transactionses) {
        this.transactionses = transactionses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="categories")
    public Set<Categories> getCategorieses() {
        return this.categorieses;
    }
    
    public void setCategorieses(Set<Categories> categorieses) {
        this.categorieses = categorieses;
    }




}


