package com.amar.expense_tracker.entity;
// Generated 11 Aug 2026, 9:58:31 pm by Hibernate Tools 7.3.13.Final


import jakarta.persistence.*;

import java.io.Serializable;
import java.util.UUID;

import org.hibernate.annotations.UuidGenerator;
import java.math.BigDecimal;
import java.util.Date;

/**
 * MonthlySummary generated by hbm2java
 */
@Entity
@Table(name="monthly_summary"
    ,schema="public"
    , uniqueConstraints = @UniqueConstraint(columnNames={"user_id", "year", "month"}) 
)
public class MonthlySummary  implements Serializable {


     private UUID id;
     private Users users;
     private int year;
     private int month;
     private BigDecimal totalCredited;
     private BigDecimal totalExpenses;
     private BigDecimal remainingAmount;
     private BigDecimal expensePercentage;
     private Date createdAt;
     private Date updatedAt;

    public MonthlySummary() {
    }

    public MonthlySummary(UUID id, Users users, int year, int month, BigDecimal totalCredited, BigDecimal totalExpenses, BigDecimal remainingAmount, BigDecimal expensePercentage, Date createdAt, Date updatedAt) {
       this.id = id;
       this.users = users;
       this.year = year;
       this.month = month;
       this.totalCredited = totalCredited;
       this.totalExpenses = totalExpenses;
       this.remainingAmount = remainingAmount;
       this.expensePercentage = expensePercentage;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
    }
   
     @Id 
     @GeneratedValue 
     @UuidGenerator 

    
    @Column(name="id", unique=true, nullable=false)
    public UUID getId() {
        return this.id;
    }
    
    public void setId(UUID id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    
    @Column(name="year", nullable=false)
    public int getYear() {
        return this.year;
    }
    
    public void setYear(int year) {
        this.year = year;
    }

    
    @Column(name="month", nullable=false)
    public int getMonth() {
        return this.month;
    }
    
    public void setMonth(int month) {
        this.month = month;
    }

    
    @Column(name="total_credited", nullable=false, precision=19, scale=4)
    public BigDecimal getTotalCredited() {
        return this.totalCredited;
    }
    
    public void setTotalCredited(BigDecimal totalCredited) {
        this.totalCredited = totalCredited;
    }

    
    @Column(name="total_expenses", nullable=false, precision=19, scale=4)
    public BigDecimal getTotalExpenses() {
        return this.totalExpenses;
    }
    
    public void setTotalExpenses(BigDecimal totalExpenses) {
        this.totalExpenses = totalExpenses;
    }

    
    @Column(name="remaining_amount", nullable=false, precision=19, scale=4)
    public BigDecimal getRemainingAmount() {
        return this.remainingAmount;
    }
    
    public void setRemainingAmount(BigDecimal remainingAmount) {
        this.remainingAmount = remainingAmount;
    }

    
    @Column(name="expense_percentage", nullable=false, precision=7, scale=4)
    public BigDecimal getExpensePercentage() {
        return this.expensePercentage;
    }
    
    public void setExpensePercentage(BigDecimal expensePercentage) {
        this.expensePercentage = expensePercentage;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false, length=35)
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at", nullable=false, length=35)
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }




}


