package com.amar.expense_tracker.entity;
// Generated 11 Aug 2026, 9:58:31 pm by Hibernate Tools 7.3.13.Final


import jakarta.persistence.*;

import java.io.Serializable;
import java.util.UUID;

import org.hibernate.annotations.UuidGenerator;
import java.util.Date;

/**
 * RefreshTokens generated by hbm2java
 */
@Entity
@Table(name="refresh_tokens"
    ,schema="public"
    , uniqueConstraints = @UniqueConstraint(columnNames="token_hash") 
)
public class RefreshTokens  implements Serializable {


     private UUID id;
     private Users users;
     private String tokenHash;
     private Date expiresAt;
     private boolean revoked;
     private Date createdAt;

    public RefreshTokens() {
    }

    public RefreshTokens(UUID id, Users users, String tokenHash, Date expiresAt, boolean revoked, Date createdAt) {
       this.id = id;
       this.users = users;
       this.tokenHash = tokenHash;
       this.expiresAt = expiresAt;
       this.revoked = revoked;
       this.createdAt = createdAt;
    }
   
     @Id 
     @GeneratedValue 
     @UuidGenerator 

    
    @Column(name="id", unique=true, nullable=false)
    public UUID getId() {
        return this.id;
    }
    
    public void setId(UUID id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    
    @Column(name="token_hash", unique=true, nullable=false, length=255)
    public String getTokenHash() {
        return this.tokenHash;
    }
    
    public void setTokenHash(String tokenHash) {
        this.tokenHash = tokenHash;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="expires_at", nullable=false, length=35)
    public Date getExpiresAt() {
        return this.expiresAt;
    }
    
    public void setExpiresAt(Date expiresAt) {
        this.expiresAt = expiresAt;
    }

    
    @Column(name="revoked", nullable=false)
    public boolean isRevoked() {
        return this.revoked;
    }
    
    public void setRevoked(boolean revoked) {
        this.revoked = revoked;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false, length=35)
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }




}


