package com.amar.expense_tracker.entity;
// Generated 11 Aug 2026, 9:58:31 pm by Hibernate Tools 7.3.13.Final


import jakarta.persistence.*;

import java.io.Serializable;
import java.util.UUID;

import org.hibernate.annotations.UuidGenerator;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Statements generated by hbm2java
 */
@Entity
@Table(name="statements"
    ,schema="public"
)
public class Statements  implements Serializable {


     private UUID id;
     private Accounts accounts;
     private Users users;
     private String fileName;
     private String storageKey;
     private String statementType;
     private Date statementStartDate;
     private Date statementEndDate;
     private String status;
     private Date uploadedAt;
     private Date processedAt;
     private String errorMessage;
     private Set<Transactions> transactionses = new HashSet<Transactions>(0);

    public Statements() {
    }

	
    public Statements(UUID id, Accounts accounts, Users users, String fileName, String storageKey, String statementType, String status, Date uploadedAt) {
        this.id = id;
        this.accounts = accounts;
        this.users = users;
        this.fileName = fileName;
        this.storageKey = storageKey;
        this.statementType = statementType;
        this.status = status;
        this.uploadedAt = uploadedAt;
    }
    public Statements(UUID id, Accounts accounts, Users users, String fileName, String storageKey, String statementType, Date statementStartDate, Date statementEndDate, String status, Date uploadedAt, Date processedAt, String errorMessage, Set<Transactions> transactionses) {
       this.id = id;
       this.accounts = accounts;
       this.users = users;
       this.fileName = fileName;
       this.storageKey = storageKey;
       this.statementType = statementType;
       this.statementStartDate = statementStartDate;
       this.statementEndDate = statementEndDate;
       this.status = status;
       this.uploadedAt = uploadedAt;
       this.processedAt = processedAt;
       this.errorMessage = errorMessage;
       this.transactionses = transactionses;
    }
   
     @Id 
     @GeneratedValue 
     @UuidGenerator 

    
    @Column(name="id", unique=true, nullable=false)
    public UUID getId() {
        return this.id;
    }
    
    public void setId(UUID id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="account_id", nullable=false)
    public Accounts getAccounts() {
        return this.accounts;
    }
    
    public void setAccounts(Accounts accounts) {
        this.accounts = accounts;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    
    @Column(name="file_name", nullable=false, length=255)
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    
    @Column(name="storage_key", nullable=false, length=500)
    public String getStorageKey() {
        return this.storageKey;
    }
    
    public void setStorageKey(String storageKey) {
        this.storageKey = storageKey;
    }

    
    @Column(name="statement_type", nullable=false)
    public String getStatementType() {
        return this.statementType;
    }
    
    public void setStatementType(String statementType) {
        this.statementType = statementType;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="statement_start_date", length=13)
    public Date getStatementStartDate() {
        return this.statementStartDate;
    }
    
    public void setStatementStartDate(Date statementStartDate) {
        this.statementStartDate = statementStartDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="statement_end_date", length=13)
    public Date getStatementEndDate() {
        return this.statementEndDate;
    }
    
    public void setStatementEndDate(Date statementEndDate) {
        this.statementEndDate = statementEndDate;
    }

    
    @Column(name="status", nullable=false)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="uploaded_at", nullable=false, length=35)
    public Date getUploadedAt() {
        return this.uploadedAt;
    }
    
    public void setUploadedAt(Date uploadedAt) {
        this.uploadedAt = uploadedAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="processed_at", length=35)
    public Date getProcessedAt() {
        return this.processedAt;
    }
    
    public void setProcessedAt(Date processedAt) {
        this.processedAt = processedAt;
    }

    
    @Column(name="error_message", columnDefinition = "TEXT")
    public String getErrorMessage() {
        return this.errorMessage;
    }
    
    public void setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="statements")
    public Set<Transactions> getTransactionses() {
        return this.transactionses;
    }
    
    public void setTransactionses(Set<Transactions> transactionses) {
        this.transactionses = transactionses;
    }




}


