package com.amar.expense_tracker.entity;
// Generated 11 Aug 2026, 9:58:31 pm by Hibernate Tools 7.3.13.Final


import jakarta.persistence.*;

import java.io.Serializable;
import java.util.UUID;

import org.hibernate.annotations.UuidGenerator;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Transactions generated by hbm2java
 */
@Entity
@Table(name="transactions"
    ,schema="public"
    , uniqueConstraints = @UniqueConstraint(columnNames="transaction_hash") 
)
public class Transactions  implements Serializable {


     private UUID id;
     private Accounts accounts;
     private Statements statements;
     private Users users;
     private Categories categories;
     private Date transactionDate;
     private String description;
     private String normalizedMerchant;
     private BigDecimal amount;
     private String transactionType;
     private String source;
     private BigDecimal confidenceScore;
     private String transactionHash;
     private boolean isManuallyAdded;
     private boolean isCategoryModified;
     private Date createdAt;
     private Date updatedAt;
     private Set<AiCategorization> aiCategorizations = new HashSet<AiCategorization>(0);

    public Transactions() {
    }

	
    public Transactions(UUID id, Accounts accounts, Users users, Date transactionDate, String description, BigDecimal amount, String transactionType, String source, String transactionHash, boolean isManuallyAdded, boolean isCategoryModified, Date createdAt, Date updatedAt) {
        this.id = id;
        this.accounts = accounts;
        this.users = users;
        this.transactionDate = transactionDate;
        this.description = description;
        this.amount = amount;
        this.transactionType = transactionType;
        this.source = source;
        this.transactionHash = transactionHash;
        this.isManuallyAdded = isManuallyAdded;
        this.isCategoryModified = isCategoryModified;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }
    public Transactions(UUID id, Accounts accounts, Statements statements, Users users, Categories categories, Date transactionDate, String description, String normalizedMerchant, BigDecimal amount, String transactionType, String source, BigDecimal confidenceScore, String transactionHash, boolean isManuallyAdded, boolean isCategoryModified, Date createdAt, Date updatedAt, Set<AiCategorization> aiCategorizations) {
       this.id = id;
       this.accounts = accounts;
       this.statements = statements;
       this.users = users;
       this.categories = categories;
       this.transactionDate = transactionDate;
       this.description = description;
       this.normalizedMerchant = normalizedMerchant;
       this.amount = amount;
       this.transactionType = transactionType;
       this.source = source;
       this.confidenceScore = confidenceScore;
       this.transactionHash = transactionHash;
       this.isManuallyAdded = isManuallyAdded;
       this.isCategoryModified = isCategoryModified;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.aiCategorizations = aiCategorizations;
    }
   
    @Id
    @GeneratedValue
    @UuidGenerator
    @Column(name="id", unique=true, nullable=false)
    public UUID getId() {
        return this.id;
    }
    
    public void setId(UUID id) {
        this.id = id;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="account_id", nullable=false)
    public Accounts getAccounts() {
        return this.accounts;
    }
    
    public void setAccounts(Accounts accounts) {
        this.accounts = accounts;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="statement_id")
    public Statements getStatements() {
        return this.statements;
    }
    
    public void setStatements(Statements statements) {
        this.statements = statements;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="category_id")
    public Categories getCategories() {
        return this.categories;
    }
    
    public void setCategories(Categories categories) {
        this.categories = categories;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="transaction_date", nullable=false, length=13)
    public Date getTransactionDate() {
        return this.transactionDate;
    }
    
    public void setTransactionDate(Date transactionDate) {
        this.transactionDate = transactionDate;
    }

    
    @Column(name="description", nullable=false, columnDefinition = "TEXT")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="normalized_merchant", length=255)
    public String getNormalizedMerchant() {
        return this.normalizedMerchant;
    }
    
    public void setNormalizedMerchant(String normalizedMerchant) {
        this.normalizedMerchant = normalizedMerchant;
    }

    
    @Column(name="amount", nullable=false, precision=19, scale=4)
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    
    @Column(name="transaction_type", nullable=false)
    public String getTransactionType() {
        return this.transactionType;
    }
    
    public void setTransactionType(String transactionType) {
        this.transactionType = transactionType;
    }

    
    @Column(name="source", nullable=false)
    public String getSource() {
        return this.source;
    }
    
    public void setSource(String source) {
        this.source = source;
    }

    
    @Column(name="confidence_score", precision=5, scale=4)
    public BigDecimal getConfidenceScore() {
        return this.confidenceScore;
    }
    
    public void setConfidenceScore(BigDecimal confidenceScore) {
        this.confidenceScore = confidenceScore;
    }

    
    @Column(name="transaction_hash", unique=true, nullable=false, length=128)
    public String getTransactionHash() {
        return this.transactionHash;
    }
    
    public void setTransactionHash(String transactionHash) {
        this.transactionHash = transactionHash;
    }

    
    @Column(name="is_manually_added", nullable=false)
    public boolean isIsManuallyAdded() {
        return this.isManuallyAdded;
    }
    
    public void setIsManuallyAdded(boolean isManuallyAdded) {
        this.isManuallyAdded = isManuallyAdded;
    }

    
    @Column(name="is_category_modified", nullable=false)
    public boolean isIsCategoryModified() {
        return this.isCategoryModified;
    }
    
    public void setIsCategoryModified(boolean isCategoryModified) {
        this.isCategoryModified = isCategoryModified;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false, length=35)
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at", nullable=false, length=35)
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="transactions")
    public Set<AiCategorization> getAiCategorizations() {
        return this.aiCategorizations;
    }
    
    public void setAiCategorizations(Set<AiCategorization> aiCategorizations) {
        this.aiCategorizations = aiCategorizations;
    }




}


