package com.amar.expense_tracker.entity;
// Generated 11 Aug 2026, 9:58:31 pm by Hibernate Tools 7.3.13.Final


import jakarta.persistence.*;

import java.io.Serializable;
import java.util.UUID;

import org.hibernate.annotations.UuidGenerator;
import java.util.Date;

/**
 * UserCategoryRules generated by hbm2java
 */
@Entity
@Table(name="user_category_rules"
    ,schema="public"
)
public class UserCategoryRules  implements Serializable {


     private UUID id;
     private Users users;
     private Categories categories;
     private String merchantPattern;
     private int priority;
     private Date createdAt;
     private Date updatedAt;

    public UserCategoryRules() {
    }

    public UserCategoryRules(UUID id, Users users, Categories categories, String merchantPattern, int priority, Date createdAt, Date updatedAt) {
       this.id = id;
       this.users = users;
       this.categories = categories;
       this.merchantPattern = merchantPattern;
       this.priority = priority;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
    }
   
     @Id
     @GeneratedValue
     @UuidGenerator
    @Column(name="id", unique=true, nullable=false)
    public UUID getId() {
        return this.id;
    }
    
    public void setId(UUID id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="category_id", nullable=false)
    public Categories getCategories() {
        return this.categories;
    }
    
    public void setCategories(Categories categories) {
        this.categories = categories;
    }

    
    @Column(name="merchant_pattern", nullable=false, length=255)
    public String getMerchantPattern() {
        return this.merchantPattern;
    }
    
    public void setMerchantPattern(String merchantPattern) {
        this.merchantPattern = merchantPattern;
    }

    
    @Column(name="priority", nullable=false)
    public int getPriority() {
        return this.priority;
    }
    
    public void setPriority(int priority) {
        this.priority = priority;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false, length=35)
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at", nullable=false, length=35)
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }




}


