package com.amar.expense_tracker.entity;
// Generated 11 Aug 2026, 9:58:31 pm by Hibernate Tools 7.3.13.Final


import jakarta.persistence.*;

import java.io.Serializable;
import java.util.UUID;

import org.hibernate.annotations.UuidGenerator;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="users"
    ,schema="public"
    , uniqueConstraints = @UniqueConstraint(columnNames="email") 
)
public class Users  implements Serializable {


     private UUID id;
     private String name;
     private String email;
     private String passwordHash;
     private Date createdAt;
     private Date updatedAt;
     private Set<UserCategoryRules> userCategoryRuleses = new HashSet<UserCategoryRules>(0);
     private Set<CategoryMonthlySummary> categoryMonthlySummaries = new HashSet<CategoryMonthlySummary>(0);
     private Set<MonthlySummary> monthlySummaries = new HashSet<MonthlySummary>(0);
     private Set<RefreshTokens> refreshTokenses = new HashSet<RefreshTokens>(0);
     private Set<Statements> statementses = new HashSet<Statements>(0);
     private Set<Accounts> accountses = new HashSet<Accounts>(0);
     private Set<Transactions> transactionses = new HashSet<Transactions>(0);

    public Users() {
    }

	
    public Users(UUID id, String name, String email, String passwordHash, Date createdAt, Date updatedAt) {
        this.id = id;
        this.name = name;
        this.email = email;
        this.passwordHash = passwordHash;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }
    public Users(UUID id, String name, String email, String passwordHash, Date createdAt, Date updatedAt, Set<UserCategoryRules> userCategoryRuleses, Set<CategoryMonthlySummary> categoryMonthlySummaries, Set<MonthlySummary> monthlySummaries, Set<RefreshTokens> refreshTokenses, Set<Statements> statementses, Set<Accounts> accountses, Set<Transactions> transactionses) {
       this.id = id;
       this.name = name;
       this.email = email;
       this.passwordHash = passwordHash;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.userCategoryRuleses = userCategoryRuleses;
       this.categoryMonthlySummaries = categoryMonthlySummaries;
       this.monthlySummaries = monthlySummaries;
       this.refreshTokenses = refreshTokenses;
       this.statementses = statementses;
       this.accountses = accountses;
       this.transactionses = transactionses;
    }
   
     @Id 
     @GeneratedValue 
     @UuidGenerator 

    
    @Column(name="id", unique=true, nullable=false)
    public UUID getId() {
        return this.id;
    }
    
    public void setId(UUID id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=150)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="email", unique=true, nullable=false, length=255)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="password_hash", nullable=false, length=255)
    public String getPasswordHash() {
        return this.passwordHash;
    }
    
    public void setPasswordHash(String passwordHash) {
        this.passwordHash = passwordHash;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false, length=35)
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at", nullable=false, length=35)
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="users")
    public Set<UserCategoryRules> getUserCategoryRuleses() {
        return this.userCategoryRuleses;
    }
    
    public void setUserCategoryRuleses(Set<UserCategoryRules> userCategoryRuleses) {
        this.userCategoryRuleses = userCategoryRuleses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="users")
    public Set<CategoryMonthlySummary> getCategoryMonthlySummaries() {
        return this.categoryMonthlySummaries;
    }
    
    public void setCategoryMonthlySummaries(Set<CategoryMonthlySummary> categoryMonthlySummaries) {
        this.categoryMonthlySummaries = categoryMonthlySummaries;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="users")
    public Set<MonthlySummary> getMonthlySummaries() {
        return this.monthlySummaries;
    }
    
    public void setMonthlySummaries(Set<MonthlySummary> monthlySummaries) {
        this.monthlySummaries = monthlySummaries;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="users")
    public Set<RefreshTokens> getRefreshTokenses() {
        return this.refreshTokenses;
    }
    
    public void setRefreshTokenses(Set<RefreshTokens> refreshTokenses) {
        this.refreshTokenses = refreshTokenses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="users")
    public Set<Statements> getStatementses() {
        return this.statementses;
    }
    
    public void setStatementses(Set<Statements> statementses) {
        this.statementses = statementses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="users")
    public Set<Accounts> getAccountses() {
        return this.accountses;
    }
    
    public void setAccountses(Set<Accounts> accountses) {
        this.accountses = accountses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="users")
    public Set<Transactions> getTransactionses() {
        return this.transactionses;
    }
    
    public void setTransactionses(Set<Transactions> transactionses) {
        this.transactionses = transactionses;
    }




}


